# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv', '~> 2.7'
gem 'json-schema', '~> 2.8'
gem 'pg', '~> 1.2'
gem 'rack', '~> 2.2'
gem 'rubocop', require: false
gem 'sequel', '~> 5.31'
gem 'sinatra', '~> 2.0'
gem 'sinatra-contrib', '~> 2.0'

group :test do
  gem 'rack-test'
  gem 'rspec'
end

group :development do
  gem 'awesome_print'
  gem 'sequel-annotate'
end
