# frozen_string_literal: true

begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec) do |t|
    t.fail_on_error = false
    t.rspec_opts = '--exclude-pattern spec/integration_test/**/*'
  end

  RSpec::Core::RakeTask.new(:integration) do |t|
    t.rspec_opts = '--pattern spec/integration_test/**/*_spec.rb'
  end

  task default: :spec
rescue LoadError
  # no rspec available
end
