# frozen_string_literal: true

begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec) do |t|
    t.fail_on_error = false
    t.rspec_opts = '--exclude-pattern spec/integration_test/**/*'
  end

  RSpec::Core::RakeTask.new(:integration) do |t|
    t.rspec_opts = '--pattern spec/integration_test/**/*_spec.rb'
  end

  task default: :spec

  task :annotate do
    require 'sequel'
    require 'dotenv'
    Dotenv.load('.env.dev', '.env')
    Sequel.connect(ENV['POSTGRES_URL'], max_connections: 4)

    # Load the models first
    Dir['models/*.rb'].each{|f| require_relative f}
  
    require 'sequel/annotate'
    Sequel::Annotate.annotate(Dir['models/*.rb'], namespace: 'Models')
  end

rescue LoadError
  # no rspec available
end
